########################################
##############REDIS접속정보##############
########################################
redis:
  - id: "r1"
    use: true
    type: "single"
    uri: ["192.168.124.238:1230"]
    timeout: 5000
    auth:
    workers: 0

  - id: "r2"
    use: false
    type: "cluster"
    uri: ["127.0.0.1:3012","127.0.0.2:3012","127.0.0.3:3012"]
    timeout: 5000
    auth:
    workers: 0